global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "kafka"
    static_configs:
      - targets: ["kafka1:7071"] # Scrape JMX Exporter from kafka1
  - job_name: "producer"
    static_configs:
      - targets: ["host.docker.internal:8000"] # Producer metrics
